### ISSUE TITLE
Invalid name when creating a child user

### ISSUE THREAD

**Issue by rustyfausak** [EasyPost/easypost-php#126]
I'm seeing strange behavior with creating a child user. It seems like supplying a child user name that contains no spaces fails.

This request fails:

```php
$child = \EasyPost\User::create(['name' => 'helloworld']);
```

With this error:

`PHP Fatal error:  Uncaught EasyPost\Error: The request was well-formed but was unable to be followed due to semantic errors. in /../vendor/easypost/easypost-php/lib/EasyPost/Requestor.php:296`

However this request succeeds:

```php
$child = \EasyPost\User::create(['name' => 'hello world']);
```

Am I missing something obvious? Are there requirements for child user names?

**Comment by Justintime50** [comment]
Hey there!

This is due to the EasyPost API expecting a user to have a first and last name (separated by a space). If you were to call the `prettyPrint()` method on the exception thrown or grab the `errors` key of the exception, you'll see the additional message contained:

```
UNPROCESSABLE_ENTITY (422): The request was well-formed but was unable to be followed due to semantic errors.
Field errors:
  field: name
  message: First and last name required.
```

Users must be created with a first and last name separated by a space. If you follow your second example, you'll be all set!
