### ISSUE TITLE
[Feat]: Is there a way to retrieve all available pickup services only by carrier?

### ISSUE THREAD

**Issue by partakone** [EasyPost/easypost-php#207]
### Feature Request Is New

- [ ] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

Hello, I was building an integration for an e-commere site and stubbled upon an unsolvable problem (at least for my puny-tiny brain) - how am I supposed to know the correct and valid name of the pickup service for a carrier to use in API? I can't even get lowest_rate, I've tried every carrier by name, and stuff like "PriorityMailExpress" from carrier site as a service name but still no use.

Maybe I've missed something??? Wouldn't that be nice to have an option to request all available services for a specific shipment/address?

**Comment by nwithan8** [comment]
We are discussing this internally. For now, the API docs is the official list of carriers and services.

**Comment by Justintime50** [comment]
Hey @partakone, great question. You can retrieve a list of carrier types via https://www.easypost.com/docs/api#carrier-types which will include the carrier names. Similarly, we have listed the available service levels per carrier here: https://www.easypost.com/docs/api#service-levels. You'll need to make sure that you have the carrier accounts in question added to your EasyPost account, this can be accomplished easily by logging into your EasyPost Dashboard and adding credentials for each carrier you have an account with. Service levels get returned based on what carriers you have configured on your account as well as the data of the shipment (some carriers don't service certain addresses, etc).

As for the ability to retrieve the possible list of services, this is something we are actively exploring at the API level. In the meantime, our support team would be an excellent resource for these kinds of questions as they deal with all of our carriers daily and know the nuances of what will and won't work with each. They can be reached via support@easypost.com. I hope this overview was helpful; otherwise our support team will be your next best option for additional details.
