### ISSUE TITLE
[Bug]: Two Files Included That Don't Exist

### ISSUE THREAD

**Issue by mwrouse** [EasyPost/easypost-php#211]
### Software Version

5.5.0

### Language Version

English

### Operating System

Yes

### What happened?

Importing library causes error since CreditCard.php and PaymentMethod.php don't exist but are imported in lib/easypost.php

### What was expected?

For it to work

**Comment by Justintime50** [comment]
Hey there, I've created #212 to fix this problem. It wasn't caught by us because our test suite uses the auto loader which doesn't raise this error (I assume you are manually requiring this library?) I'd suggest using Composer's autoloader in the future as it's much better at handling these kind of things; however, I added a regression test to protect against this happening again in the future.

**Comment by Justintime50** [comment]
`v5.5.1` has been released with this fix. Please update and let us know if there is anything else related to this issue.
