### ISSUE TITLE
retrieving with tracking_code does not return shipment id

### ISSUE THREAD

**Issue by mbeale** [EasyPost/easypost-php#3]
tracking_code is set as ID.

**Comment by Justintime50** [comment]
Trackers cannot be retrieved with a tracking code and instead will need to be retrieved by a tracking ID (they may have been able to be retrieved by a tracking code years ago). Our documentation on this can be found here: https://www.easypost.com/docs/api/curl#retrieve-a-tracker. Retrieving a tracker will also retrieve it's associated `shipment_id`.

Please let me know if I'm misunderstanding this issue here.
