### ISSUE TITLE
[Bug]: Unable to create address

### ISSUE THREAD

**Issue by jp92004** [EasyPost/easypost-php#302]
### Software Version

6.7.0

### Language Version

8.1

### Operating System

Linux

### What happened?

Ah sorry to bug you Nate!

1.Create client with API
2. Try to create address

...

### What was expected?

Should have created address

### Sample Code

```inc
$client = new \EasyPost\EasyPostClient($examplekey);
$to_address = $client->address->create(array(address stuff...));
```

### Relevant logs

```sh
Fatal error: Uncaught Error: Class "GuzzleHttp\Client" not found in ...
```

**Comment by jp92004** [comment]
Oh forgot to mention that, as with the last report, library was downloaded and included manually (no composer)

**Comment by jp92004** [comment]
> Can you provide an example of how you are requiring the easypost library so we can attempt to recreate it?

Sure!
include_once $_SERVER["DOCUMENT_ROOT"] . '/pathtolib/lib/easypost.php';

**Comment by Justintime50** [comment]
Thanks! Most likely, because the error is expressing it can't find Guzzle which is one of our dependencies and you appear to only be including the EasyPost library itself instead of the autoloader, it can't find the other dependencies. Can you try something more along the lines of this? `require_once("/path/to/vendor/easypost/autoload.php");`

Let me know if that fixes things.

**Comment by Justintime50** [comment]
Fair point! I'll clarify the README
