### ISSUE TITLE
[Feat]: Support Persistent GuzzleClient Instance

### ISSUE THREAD

**Issue by NHZEX** [EasyPost/easypost-php#315]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

Support persistent GuzzleClient instance to avoid re-instantiating the client for each request, resulting in improved performance.

https://github.com/EasyPost/easypost-php/blob/8b3b9fae54fd0ce19cf0b4cd7a3c75c4ad032ae5/lib/EasyPost/Http/Requestor.php#L208-L224

**Comment by Justintime50** [comment]
Hey @NHZEX thanks for the suggestions! Do you have a suggestion on where to place the Guzzle instantiation? I would assume the most logical place would be inside of the EasyPost client?

As for network proxies and replacing HTTP clients, this is something the team has definitely considered! We'll take this feedback to our product team. In the meantime, it would be super helpful if you could break up the above three asks into separate issues so that we can address each individually. We'd be able to get to each much easier if broken out in that manner.

**Comment by NHZEX** [comment]
> Hey @NHZEX thanks for the suggestions! Do you have a suggestion on where to place the Guzzle instantiation? I would assume the most logical place would be inside of the EasyPost client?

I agree that the most logical place is inside the EasyPost client.

> As for network proxies and replacing HTTP clients, this is something the team has definitely considered! We'll take this feedback to our product team. In the meantime, it would be super helpful if you could break up the above three asks into separate issues so that we can address each individually. We'd be able to get to each much easier if broken out in that manner.

OK.
