### ISSUE TITLE
[Bug]: Adding out-of-range insurance amount to a shipment during the `buy` method yields an error with no readable message

### ISSUE THREAD

**Issue by designosis** [EasyPost/easypost-php#353]
### Software Version

v7.4.2

### Language Version

PHP

### Operating System

Unix, LAMP stack

### What happened?

The below sample code works fine when the `insurance` value is `5000`. At `5001`, however, a non-useful error is returned:
```
{
    code: "INSURANCE.AMOUNT.ABOVE_MAXIMUM",
    errors: null
}
```

### What was expected?

As with other errors, I'd expect `\EasyPost\Exception\Api\ApiException` to return an error with a readable `message` string.

Is this a common occurrence? What I'm really asking is should I build a table from https://docs.easypost.com/guides/errors-guide#error-codes to reliably get a readable message for any given code?

### Sample Code

```php
try {
    $shipment = $client->shipment->create([
        'from_address' => $config['shipping'],
        'to_address' => $ship_to,
        'parcel' => [
            'length' => 20.2,
            'width'  => 10.9,
            'height' => 5,
            'weight' => 65.9,
        ],
    ]);
    $res = $client->shipment->buy( $shipment->id, [
        'rate'      => $shipment->lowestRate(),
        'insurance' => 5001,
    ]);
} catch (\EasyPost\Exception\Api\ApiException $error) {
    $res = json_encode($error);
}

$output = json_decode($res, true);
echo '<pre>'.json_encode($output, JSON_PRETTY_PRINT).'</pre>';
```

**Comment by designosis** [comment]
Apologies, nevermind

**Comment by designosis** [comment]
Apologies, never mind.

**Comment by Justintime50** [comment]
Thanks for reporting this!

Others have identified similar issues related to insurance. This is most likely an API issue. It's been reported internally and we'll see about a fix. You should not need to build your own error handling to get the error, this should be specific to insurance only.

**Comment by Justintime50** [comment]
After looking into this, the error is properly returned but the code you are using isn't grabbing the right details. Here is a corrected sample which should get you the entire error:

```php
} catch (\EasyPost\Exception\Api\ApiException $error) {
    $res = $error;
    $body = $error->getHttpBody();
    echo $body;
}
```

By calling the `getHttpBody()` method on the error instead of (de)serializing the error manually, you can get the error in its entirety which includes the `message` field along with the previous `code` and `errors` keys. There are additional methods you can call on an error, the best place to look for usage is probably the [testError](https://github.com/EasyPost/easypost-php/blob/14ab83965b191dd4e6f7c1a1c08d1011e034ecc1/test/EasyPost/ErrorTest.php#L34) test in the test suite which calls and shows all the methods of an error in this library.

Let us know if that doesn't get you what you need.
