### ISSUE TITLE
Get all the service levels of a carrier account

### ISSUE THREAD

**Issue by lukeholder** [EasyPost/easypost-php#36]
Does this package provide a way to get all service levels of a carrier account? I can't see how to do this in the API docs either? Thanks.

**Comment by att14** [comment]
https://www.easypost.com/service-levels-and-parcels

Seems like a decent addition to the api in the future. I'll add it to the backlog.

**Comment by lukeholder** [comment]
Thanks @att14 I was going to mention parcels also. It would be great if they could both be added to the API. In the meantime is there a csv or json dump I could get? Or do I have to screen scrape?

**Comment by att14** [comment]
For now you'll need to copy paste from the website.

**Comment by michaelchemani** [comment]
Hi, I was wondering if you have some news about providing a way to get all service levels of a carrier account? Is it in the pipeline already?

Thank you

**Comment by att14** [comment]
No news, unfortunately this is more complicated than it seems because many of the service levels are directly from the carrier and we have no static mapping in our code. It also isn't a highly requested feature because the rating api is sufficient for most use cases.

If you explain your use case either here or to support@easypost.com we might be able to offer some advice or alternatives.

**Comment by michaelchemani** [comment]
For example, a customer who is using USPS want to only display certain service levels to his client. This service levels could be configured before being displayed but in order to do that I will need the entire list. Is it clear enough?
