### ISSUE TITLE
FedEx rates not calculating?

### ISSUE THREAD

**Issue by iamarkdev** [EasyPost/easypost-php#4]
I'm attempting to calculate fedex shipping rates. I'm using the following to generate a shipment and then pulling calculated rates from it:

$shipment = Shipment::create(array(
                    'from_address' => $this->fromAddress,
                    'to_address' => $this->toAddress,
                    'parcel' => $this->parcel,
                    'options' => array(
                        'residential_to_address' => 1
                    )
                ));

I'm receiving all UPS / USPS rates without any problem for both domestic and international, however I'm not getting any sort of response for FedEx rates - what's going on? I've double checked my FedEx credentials set on the EasyPost web portal, and they are correct. FedEx also says "Enabled" under carriers in my EasyPost account.

**Comment by kuntal33** [comment]
Hi,
I set that option "delivery_duty_paid= false" but it will not change the "Terms of Sale" from "DDU" to 'FCA'.

Free Carrier (FCA/FOB): Free Carrier at a named port of export. The seller quotes the buyer a price that covers all costs up to and including delivery of goods aboard an overseas vessel (e.g. airplane).

Delivered Duty Unpaid (DDU): The seller fulfills his obligation to deliver when the goods have been made available at the named place. The seller bears the costs and risks involved in bringing the goods to that place but not the costs and risks of clearing customs.

This is the difference between DDU and FCA.

I want to set FCA instead of DDU in my commercial invoice form using API.

Please tell me that how i can change this value using api?

**Comment by zardilior** [comment]
This problem is still happening I am receiving half of my rates in $0, I am during test mode but cannot afford going live without ensurance that my tests are well. Is there any reason and if it is an error why does it return 0 price instead of sending an error.

**Comment by att14** [comment]
Hi @zardilior, this appears to be an api issue and not with this client. Can you email us at support@easypost.com and provide us with a shipment id?

**Comment by zardilior** [comment]
@att14 effectively it was an api issue, a request limit reached during intense testing of our software
