### ISSUE TITLE
Static methods and multiple classes are very difficult to test

### ISSUE THREAD

**Issue by chinyeung** [EasyPost/easypost-php#49]
We are using the Easypost PHP package within our own service class.  In order to do full unit testing, the standard practice is to use dependency injection.  However, Easypost makes use of multiple classes to perform functions, making it very difficult to mock the objects because for any class, we would need to inject far too many EasyPost classes to be practical.

The abstract class on the EasyPost\EasyPost package is also impossible to instantiate, and thus it is impossible to mock it directly.  

It would be very helpful if static methods could be avoided or in the very least act as a proxy to a normal dynamic service class(es) that could be easily mocked and tested.

**Comment by att14** [comment]
Do you have any examples of low hanging fruit we could change to make this easier? Otherwise, this seems pretty open ended and a large rewrite of the current code. We always accept pull requests if you are inclined to take this on yourself.

**Comment by fireproofsocks** [comment]
+1.  The implication here is that the code and classes are structured problematically.  There may not be an easy fix.  This is a good example of why static methods are problematic and should be avoided in most scenarios.

**Comment by colorninja** [comment]
Are there plans to change the structure in the near future? DI would be nice.

**Comment by Justintime50** [comment]
Is anyone involved able to provide an example per @att14 request? cc @chinyeung

**Comment by Justintime50** [comment]
This has been opened for a few years now with no follow up. I'm going to close this for now. If anyone is interested or can provide additional details on what they had in mind, I'm open to reopening this and taking a look.

**Comment by fireproofsocks** [comment]
FWIW: I don't think any observer here was willing to go through the _substantial_ work to significantly modify the codebase to expunge all (or nearly all) cases where `public static function` was used  without more interactions from the repository owner(s) because it's unlikely such a massive PR would be merged, let alone welcome, without some discussion first.  

Related: I would recommend [Jeffery Way's "Laravel Testing Decoded"](https://leanpub.com/laravel-testing-decoded) as a good primer on structuring applications to facilitate testing.  A couple key takeaways are to avoid static methods and avoid instantiating objects inside functions because they make that code more difficult to test.

**Comment by jontsai** [comment]
I agree with the points made by OP on the original issue. However, in order to introduce support for this, it would require what amounts to a full rewrite of the PHP client library, and it would definitely be a major version upgrade.

We are open to doing this if it makes sense for the library going forward, but would also have to balance this with other priorities on our current roadmap.
