### ISSUE TITLE
Multi-piece-shipment USPS

### ISSUE THREAD

**Issue by adnangs** [EasyPost/easypost-php#66]
Hey,
Does Easypost PHP API supports, multi parcels in same shipment??

**Comment by mwaldt** [comment]
The shipment objects have a 1 to 1 relationship with parcel objects. You can use [Order](https://www.easypost.com/docs/api/php#orders-create-codesample) objects for multi-piece shipments.

I would also advise sending questions like this to support@easypost.com so that a support rep can assist you with any further questions.
